name: Sell
api: [3.0.0]
main: SellHand\Main
version: 3.0.0
author: [Muqsit]
authors: [KairusDarkSeeker, JackMD]
depend: EconomyAPI
commands:
  sell:
    description: "Sells the item in your hand or all of your inventory's contents"
    permission: sell.command
permissions:
  sell:
    default: op
    children:
      sell.hand:
        default: op
      sell.all:
        default: op
      sell.command:
        default: true
...

